### ISSUE TITLE
Suggestion: make mtrandom.h not public

### ISSUE THREAD

**Issue by MonokuroInzanaito** [Fluorohydride/ygopro#2352] opened 2021-06-06 05:02 UTC
I have seen players reproducing algorithm in `mtrandom.h` when duel starts, making their starting hand always desirable.
To make an example, the player can check their starting hand at each second, and start the duel when the good hand comes. This breaks the fairness of the duels. I believe this is due to the publicness of `mtrandom.h`.
To make the duel fair enough, I think we should change the algorithm in `mtrandom.h`, and make that algorithm only available to developers.
An alternative solution, is to add a hidden key in this algorithm, or in the process seed generation. Both ways would make players reproducing the random algorithm impossible.

**Comment by salix5** [comment] 2021-08-16 13:55
@MonokuroInzanaito 
> I have seen players reproducing algorithm in `mtrandom.h` when duel starts, making their starting hand always desirable.
> To make an example, the player can check their starting hand at each second, and start the duel when the good hand comes. This breaks the fairness of the duels. I believe this is due to the publicness of `mtrandom.h`.

As far as I know, the reason is the seed of Random Number Generator(RNG).
Mersenne Twister is a verry popular RNG, and the algorithm is public all along.

ygopro used `time(nullp)` as the seed of RNG before, and the player can easily get it.
If a player can get the seed of RNG, he can duplicate the RNG and predict the starting hand.
This is a very inappropriate approach, and I try to fix it in #2362, #2363, Fluorohydride/ygopro-core#391.

> To make the duel fair enough, I think we should change the algorithm in `mtrandom.h`, and make that algorithm only available to developers.
> An alternative solution, is to add a hidden key in this algorithm, or in the process seed generation. Both ways would make players reproducing the random algorithm impossible.

Now ygopro will generate the seed by `std::random_device`, and I think the player cannot reproduce the seed anymore.
We appreciate your kind assistance, and please let us know if there is any problem in the new approach.

**Comment by salix5** [comment] 2021-08-22 10:57
@MonokuroInzanaito 
merged into master
If you find any problem, please give us your advice.
Thank you very much!

**Closed by salix5** 2021-08-22 10:57 UTC
Labels: bug
